"""Added a test column

Revision ID: 011cde6d5a21
Revises: 07e1e3589feb
Create Date: 2024-11-14 14:18:16.018302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011cde6d5a21'
down_revision = '07e1e3589feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_column', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.drop_column('test_column')

    # ### end Alembic commands ###
