"""empty message

Revision ID: 07e1e3589feb
Revises: 1f7fc1be47f8
Create Date: 2024-11-14 09:44:23.318393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e1e3589feb'
down_revision = '1f7fc1be47f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('show', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('show_id', sa.Integer(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('show', schema=None) as batch_op:
    #     batch_op.drop_column('show_id')
    pass

    # ### end Alembic commands ###
