"""Removed test_column from show table

Revision ID: 4efe976943ef
Revises: 011cde6d5a21
Create Date: 2024-11-14 14:28:34.181014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4efe976943ef'
down_revision = '011cde6d5a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.drop_column('test_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_column', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
