"""Added seeking_artist

Revision ID: 65d297f007f5
Revises: c888ae87dfd6
Create Date: 2024-11-24 13:54:55.107251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d297f007f5'
down_revision = 'c888ae87dfd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_artist', sa.Boolean(), nullable=True))
        batch_op.drop_column('seeking_for_artist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_for_artist', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('seeking_artist')

    # ### end Alembic commands ###
