"""Rename seeking_artist to seeking_talent

Revision ID: f2ac8730bb0b
Revises: 65d297f007f5
Create Date: 2024-11-24 14:01:15.994759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ac8730bb0b'
down_revision = '65d297f007f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_talent', sa.Boolean(), nullable=True))
        batch_op.drop_column('seeking_artist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_artist', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('seeking_talent')

    # ### end Alembic commands ###
